### ISSUE TITLE
[Feat]: Auto-add CODEOWNERS to pull requests

### ISSUE THREAD

**Issue by michaelachrisco** [Shift3/DevOps-Apprenticeship-Notes#80]
### Is your feature request related to a problem? Please describe.

A good CODEOWNER file can reduce the amount of time we spend auto-adding team members to pull requests and allow more ownership of code to the specified team. 

### Describe the solution you'd like.

I would like a CODEOWNER file to be added to this repo. I would like it to contain my GitHub username, the team username, and I wold like it to look like: https://github.com/Shift3/terraform-modules/blob/develop/.github/CODEOWNERS but replace Michael Wallerts GitHub username with mine, and the team should be @Shift3/devops-apprentices. 

### Additional context

For more info on CODEOWNERS: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by NicAtak** [comment]
@michaelachrisco I tried making this file, but I am getting an error message from Github. Would you mind taking a look?  https://github.com/NicAtak/DevOps-Apprenticeship-Notes/commit/71682f8521d97684d73dee181b3ac7a333308b9a#

**Comment by NicAtak** [comment]
Hi @michaelachrisco I tried making the requested file, but github is saying there is an error. I can't figure out what the difference is between the code referenced and the one I made. Would you mind taking a look?

https://github.com/NicAtak/DevOps-Apprenticeship-Notes/blob/development/.github/CODEOWNERS

Is it because of permissions? Did I use the wrong branch?

**Comment by michaelachrisco** [comment]
@NicAtak Thanks for following up!

https://github.com/NicAtak/DevOps-Apprenticeship-Notes/ is your own repo and the CODEOWNER is only for the repo that it contained within. I and the apprentice team is only assigned to this repo: https://github.com/Shift3/DevOps-Apprenticeship-Notes

If you make a PR to this repo from your repo, you will find that it should be resolved and GitHub should stop complaining. 

Let me know if that makes sense. I can also do a quick 15 min call if necessary.

**Comment by NicAtak** [comment]
so, basically ignore Github and do a PR request?

**Comment by michaelachrisco** [comment]
In this case, yes. Normally we dont want to do that but...yeah 😃 .
